Deprecate code due x.25.
OpenHFT/Chronicle-Core pull request #590
Opened 2023-10-23 14:24 UTC by yevgenp

2023-10-23 14:35 UTC, alamar requested changes

2023-10-23 14:35 UTC, alamar commented on systemProperties.adoc
> -| `disable.thread.safety` | `false` | If enabled, threadSafetyCheck throws `IllegalStateException` in AbstractReferenceCounted.java and message thrown stating which component is not thread safe | `DI
Perhaps we need to document `disable.single.threaded.check` here?

2023-10-23 14:36 UTC, alamar commented
There are build failures.

Please also make sure that it is merged into the develop only after the 2.24 stable branch is split off.

2023-10-23 15:32 UTC, yevgenp commented on systemProperties.adoc
> -| `disable.thread.safety` | `false` | If enabled, threadSafetyCheck throws `IllegalStateException` in AbstractReferenceCounted.java and message thrown stating which component is not thread safe | `DI
Done

2023-10-24 13:49 UTC, alamar commented
Should read "remove deprecated code"

2023-10-24 14:30 UTC, peter-lawrey approved these changes

2023-10-27 17:21 UTC, alamar approved these changes

2023-10-27 17:21 UTC, alamar commented on pom.xml
> +                            <binaryCompatibilityPercentageRequired>90.5</binaryCompatibilityPercentageRequired>
Should become 100% of 2.25ea0 when it is released.

2023-10-30 04:29 UTC, merged